export * from './IAssignment'
export * from './IAuth'
export * from './ICourse'
export * from './IEvaluation'
export * from './ISubmitedAssignment'
export * from './IUser'
export * from './Jtp'

export * from './response/IAssignmentResponse'
export * from './response/IAuthResponse'
export * from './response/ICourseResponse'
export * from './response/IEvaluationResponse'
export * from './response/ISubmitedResponse'